name = "MyExample5"
uuid = "fcbdd8f7-0c33-466b-a92c-46ac68577ec6"
authors = ["Eduardo Ruy"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
